### ISSUE TITLE
API_GUIDE.d.ts

### ISSUE THREAD

**Issue by cog25** [GitMessengerBot/GitMessengerBot-Android#1]
API_GUIDE에 맞춰 만들어본 d.ts입니다

[이곳](https://doc.deno.land/https/gist.githubusercontent.com%2Fcog25%2Ffd6e6f4680ee4d6191ff88100477b514%2Fraw%2Fbab50d2f2f36030939d9997d909a7f0196388582%2Ftest.d.ts) 에서 문서처럼 보실 수 있습니당

**Comment by jisungbin** [comment]
![image](https://user-images.githubusercontent.com/40740128/116163404-a72ed600-a732-11eb-9ad5-9e28b5ff88ec.png)

**Comment by thoratica** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/40740128/116163404-a72ed600-a732-11eb-9ad5-9e28b5ff88ec.png)

https://doc.deno.land/https/gist.githubusercontent.com%2Fthoratica%2F741d206792c9f37d9725034a6de47f83%2Fraw%2Fc4af6a5f00255eeb7f77e79bf39ed3363dbd3db3%2Fapi.d.ts

포크해서 수정해봤어요

**Comment by jisungbin** [comment]
@thoratica  추후 많은 api가 변경될 예정입니다.

**Comment by thoratica** [comment]
> @thoratica  추후 많은 api가 변경될 예정입니다.

그냥 export 글자 사이에 뭔 투명 특수 문자라도 있는거 같길래 10초만에 수정한거라 상관없어요
