### ISSUE TITLE
Could not find com.balsikandar.android:crashreporter:1.1.0.

### ISSUE THREAD

**Issue by tenSunFree** [GitMessengerBot/GitMessengerBot-Android#4]
Could not find com.balsikandar.android:crashreporter:1.1.0.
<img width="591" alt="2021-07-10_042615" src="https://user-images.githubusercontent.com/23090085/125132655-33984480-e137-11eb-9c50-b97222778772.png">

Maybe try to block it.
<img width="551" alt="2021-07-10_042903" src="https://user-images.githubusercontent.com/23090085/125132830-778b4980-e137-11eb-8bfe-79311ece133f.png">

**Comment by jisungbin** [comment]
This is the version under development. It may not work.

**Comment by jisungbin** [comment]
Would you try the build on Mac OS? All development is done in a Mac OS.
