### ISSUE TITLE
error: resource style/Theme.MaterialComponents.Light.DarkActionBar

### ISSUE THREAD

**Issue by tenSunFree** [GitMessengerBot/GitMessengerBot-Android#5]
error: resource style/Theme.MaterialComponents.Light.DarkActionBar
<img width="840" alt="2021-07-10_043127" src="https://user-images.githubusercontent.com/23090085/125133047-d05ae200-e137-11eb-9811-e61a44adc799.png">

Maybe add apples com.google.android.material
<img width="595" alt="2021-07-10_043511" src="https://user-images.githubusercontent.com/23090085/125133552-98a06a00-e138-11eb-93b8-bf57dbb1073a.png">

**Comment by jisungbin** [comment]
This is the version under development. It may not work.

**Comment by jisungbin** [comment]
https://github.com/GitMessengerBot/GitMessengerBot-Android/issues/4#issuecomment-877479421
