### ISSUE TITLE
Type 'DefaultTask' property 'buildPython' doesn't have a configured value.

### ISSUE THREAD

**Issue by tenSunFree** [GitMessengerBot/GitMessengerBot-Android#6]
Type 'DefaultTask' property 'buildPython' doesn't have a configured value.
<img width="670" alt="2021-07-10_055716" src="https://user-images.githubusercontent.com/23090085/125140313-ca1f3280-e144-11eb-9301-4172ed4a6212.png">

Maybe you can block Apple related.
<img width="407" alt="2021-07-10_060557" src="https://user-images.githubusercontent.com/23090085/125140416-08b4ed00-e145-11eb-8409-93dfcf2af4bc.png">
<img width="490" alt="2021-07-10_060623" src="https://user-images.githubusercontent.com/23090085/125140421-0bafdd80-e145-11eb-83fb-ceec96ac4546.png">

**Comment by jisungbin** [comment]
This is the version under development. It may not work.

**Comment by jisungbin** [comment]
https://github.com/GitMessengerBot/GitMessengerBot-Android/issues/4#issuecomment-877479421
